### ISSUE TITLE
Allow UDP and ICMP egress from isolated network

### ISSUE THREAD

**Issue by hrak** [kubernetes-sigs/cluster-api-provider-cloudstack#220]
/kind feature

**Describe the solution you'd like**

Right now upon network creation, [the egress rule created by default only allows TCP traffic out.](https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/blob/c3f25a2e38d57cc32eeeeee3ceddfc44160444b3/pkg/cloud/isolated_network.go#L115) This blocks things like f.e. NTP, so your Kubernetes nodes are unable to sync with an external NTP pool (amongst other issues).

(Optionally?) allow UDP egress in Cloudstack firewall to resolve this.

**Comment by hrak** [comment]
What are your opinions on this? I would like to know if you agree that egress firewall should default to allow all (TCP/UDP/ICMP). If so i will create a PR.

**Comment by weizhouapache** [comment]
@hrak 
+1

**Comment by hrak** [comment]
I have the patch ready, just need to file a PR for it. Will do ASAP.

**Comment by davidjumani** [comment]
Sorry for not getting back to you sooner, but as mentioned in the PR, I think this should not be added to the CAPC code because this is not within the functionality of CAPI - It should just manage the cluster lifecycle, and not handle additional tasks such as ensuring NTP sync or ICMP works. The user should open this up or any application which integrates with CAPC.

**Comment by davidjumani** [comment]
> @davidjumani i don't quite understand this. If it is not within the functionality of CAPI to allow UDP or ICMP egress, then why is it in the functionality to allow TCP egress?

It is to allow the kubernetes endpoint to communicate with the outside world when queried (either by CAPI or the end user). Since it allows all traffic, rather than just 6443, I think it should be restricted to just this. I was able to bring up a cluster with just this port open. There might be cases where the container images or CNI images might not be present on the node, which is why I think a blanket TCP rule was added to allow for downloading these images.
I think its safer to allow only the necessary traffic (6443) and let the user manually punch holes in the firewall for the application / ntp needs (as this relates to the applications / host OS and not kubernetes operations)

However, since these are egress rules, I don't have any hard opinion on this and will support the decision the team takes :)

**Comment by chrisdoherty4** [comment]
I don't see an issue with opening up egress for these protocols. 

Kubernetes attempts to be secure out of the box and uses default allow for egress. It seems odd to me that we would block everything and require the user to perform additional steps to make their cluster capable of running applications (I'm not aware of a CAPI infrastructure provider that follows that mantra today).

I think configuring a firewall can be within scope of a CAPI infrastructure provider. The scope of a Cluster controller is to provision all necessary components to bring about a _functional_ cluster which includes configuration. Only allowing 6443 through the firewall for TCP egress  traffic seems excessive and not inline with how Kubernetes operates; I think this extends to UDP egress.

**Comment by chrisdoherty4** [comment]
> Thanks for clearing it up. Makes sense this way, however since we're opening all egress rules, I'd suggest we document this so that users are aware of the rules being opened and the reason. Documentation could also help in cases where it is a shared network, or the isolated network might not have internet access and there might be further action required (either in or outside CloudStack)

Great callout. Documentation can be invaluable.

**Comment by weizhouapache** [comment]
@hrak 
I believe this has been fixed via #235 , right ?

**Comment by davidjumani** [comment]
@weizhouapache I think just some additional documentation might be necessary around this 
https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/235#discussion_r1222237578

Shall we keep this open until it is fully documented ?

**Comment by hrak** [comment]
> @hrak I believe this has been fixed via #235 , right ?

Yep. I'm ok with merging and closing. I don't see why we need to document situations that are outside of the responsibility of this provider or Cloudstack tbh.

**Comment by rohityadavcloud** [comment]
Likely fixed by https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/235  pl re-open if that's not the case @hrak
