### ISSUE TITLE
Free IP check fails when using a domain admin account

### ISSUE THREAD

**Issue by chrisdoherty4** [kubernetes-sigs/cluster-api-provider-cloudstack#292]
/kind bug

**What steps did you take and what happened:**

When creating clusters using a domain admin account that attaches VMs to a shared network in the ROOT domain the domain admin account cannot see free IP addresses (it can only see IPs associated with VMs in the subdomain). This leads to the free IP check failing even though the VM could create successfully.

**What did you expect to happen:**

The free IP check succeeds.

**Anything else you would like to add:**

[Shared network free IP check.](https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/blob/main/pkg/cloud/instance.go#L261)

**Environment:**

- CloudStack 4.17.2.
- [Tip of CAPC main branch.](https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/commit/4ccf853371507fc686f1d1bce5a2746ef954875c)

**Comment by chrisdoherty4** [comment]
The code has been reverted in #294.

**Comment by rohityadavcloud** [comment]
I've raised an issue upstream to see if we can have CloudStack allow listing free IPs in shared networks https://github.com/apache/cloudstack/issues/7817

**Comment by rohityadavcloud** [comment]
Update - this has been fixed upstream with 4.18.1.0 release and https://github.com/apache/cloudstack/pull/7898 The PR #294 would likely need to be reverted if required, as a domain and normal user-account we should expect to be able to specify IP address when using a shared network.

**Comment by g-gaston** [comment]
From what I can see, the original issue was fixed by #294 
If we want to add the validation back now that upstream cloudstack released the fix, I think that probably requires a new issue in this repo. Also we probably need to make the validation dependent on the cloudstack version the user runs, since nothing guarantees users will have updated

Closing this but pls feel free to reopen if you disagree or just create a new issue
/close
